### ISSUE TITLE
isBSDOs() vs isBsdOs()

### ISSUE THREAD

**Issue by rotexdegba** [trntv/probe#18]
The method **[isBsdOs](https://github.com/trntv/probe/blob/0daf0b75dfd983fef0fbbf04cf37afcadd71bef8/src/Provider/ProviderInterface.php#L105)** in **ProviderInterface** is named **[isBSDOs](https://github.com/trntv/probe/blob/0daf0b75dfd983fef0fbbf04cf37afcadd71bef8/src/Provider/AbstractProvider.php#L53)** in **AbstractProvider** . I believe they should both be named using the same alphabet case.

**Comment by trntv** [comment]
Can you make PR to change it?

**Comment by rotexdegba** [comment]
Do you want me to make both **isBsdOs** ?

**Comment by trntv** [comment]
Yes

**Comment by rotexdegba** [comment]
[Done](https://github.com/trntv/probe/pull/20)

**Comment by rotexdegba** [comment]
Can I close this issue?
